2019/08/10 04:49:28.337|Error|6|80000037-0000-f500-b63f-84710c7967bb|POST http://localhost:50663/api/grades/for-teachers/3|eGradeBook.Services.Exceptions.TakingNotFoundException: Student 12 is not taking the course 1 with teacher 3 in classroom 4
   at eGradeBook.Services.TakingsService.GetTaking(Int32 courseId, Int32 teacherId, Int32 classRoomId, Int32 studentId) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\TakingsService.cs:line 131
   at eGradeBook.Services.GradesService.CreateGrade(Int32 courseId, Int32 teacherId, Int32 classRoomId, Int32 studentId, Int32 schoolTerm, DateTime assigned, Int32 gradePoint, String notes) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 73
   at eGradeBook.Services.GradesService.CreateGrade(GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 111
   at eGradeBook.Services.GradesService.CreateGradeDto(GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 133
   at eGradeBook.Controllers.GradesController.CreateGradeAsTeacher(Int32 teacherId, GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Controllers\GradesController.cs:line 124
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() courseId: 1;teacherId: 3;classRoomId: 4;studentId: 12;MS_LoggedBy: System.Collections.Generic.List`1[System.Object]
2019/08/10 04:52:34.799|Error|43|8000003d-0000-f500-b63f-84710c7967bb|POST http://localhost:50663/api/grades/for-teachers/3|eGradeBook.Services.Exceptions.TakingNotFoundException: Student 11 is not taking the course 2 with teacher 3 in classroom 2
   at eGradeBook.Services.TakingsService.GetTaking(Int32 courseId, Int32 teacherId, Int32 classRoomId, Int32 studentId) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\TakingsService.cs:line 131
   at eGradeBook.Services.GradesService.CreateGrade(Int32 courseId, Int32 teacherId, Int32 classRoomId, Int32 studentId, Int32 schoolTerm, DateTime assigned, Int32 gradePoint, String notes) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 73
   at eGradeBook.Services.GradesService.CreateGrade(GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 111
   at eGradeBook.Services.GradesService.CreateGradeDto(GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 133
   at eGradeBook.Controllers.GradesController.CreateGradeAsTeacher(Int32 teacherId, GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Controllers\GradesController.cs:line 124
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() courseId: 2;teacherId: 3;classRoomId: 2;studentId: 11;MS_LoggedBy: System.Collections.Generic.List`1[System.Object]
2019/08/10 04:55:15.386|Error|25|8000013b-0000-fb00-b63f-84710c7967bb|POST http://localhost:50663/api/grades/for-teachers/3|eGradeBook.Services.Exceptions.TakingNotFoundException: Student 10 is not taking the course 1 with teacher 3 in classroom 2
   at eGradeBook.Services.TakingsService.GetTaking(Int32 courseId, Int32 teacherId, Int32 classRoomId, Int32 studentId) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\TakingsService.cs:line 131
   at eGradeBook.Services.GradesService.CreateGrade(Int32 courseId, Int32 teacherId, Int32 classRoomId, Int32 studentId, Int32 schoolTerm, DateTime assigned, Int32 gradePoint, String notes) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 73
   at eGradeBook.Services.GradesService.CreateGrade(GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 111
   at eGradeBook.Services.GradesService.CreateGradeDto(GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 133
   at eGradeBook.Controllers.GradesController.CreateGradeAsTeacher(Int32 teacherId, GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Controllers\GradesController.cs:line 124
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() courseId: 1;teacherId: 3;classRoomId: 2;studentId: 10;MS_LoggedBy: System.Collections.Generic.List`1[System.Object]
2019/08/10 04:55:28.006|Error|13|8000013d-0000-fb00-b63f-84710c7967bb|POST http://localhost:50663/api/grades/for-teachers/3|eGradeBook.Services.Exceptions.TakingNotFoundException: Student 10 is not taking the course 3 with teacher 3 in classroom 2
   at eGradeBook.Services.TakingsService.GetTaking(Int32 courseId, Int32 teacherId, Int32 classRoomId, Int32 studentId) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\TakingsService.cs:line 131
   at eGradeBook.Services.GradesService.CreateGrade(Int32 courseId, Int32 teacherId, Int32 classRoomId, Int32 studentId, Int32 schoolTerm, DateTime assigned, Int32 gradePoint, String notes) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 73
   at eGradeBook.Services.GradesService.CreateGrade(GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 111
   at eGradeBook.Services.GradesService.CreateGradeDto(GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Services\GradesService.cs:line 133
   at eGradeBook.Controllers.GradesController.CreateGradeAsTeacher(Int32 teacherId, GradeDto gradeDto) in C:\Users\Varga\source\repos\eGradeBook\eGradeBook\Controllers\GradesController.cs:line 124
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() courseId: 3;teacherId: 3;classRoomId: 2;studentId: 10;MS_LoggedBy: System.Collections.Generic.List`1[System.Object]
